name: Build
on:
  release:
jobs:
  build_and_pub:
    runs-on: [ubuntu-latest]
    env:
      DOCKER_REPO: ${{ secrets.DOCKER_REPO }}
      DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
      DOCKER_JSON_KEY: ${{ secrets.DOCKER_JSON_KEY }}
    steps:
      - name: Login to registry
        run: echo ${{ secrets.DOCKER_JSON_KEY }} | docker login --username json_key --password-stdin $DOCKER_REPO
      - uses: actions/checkout@master
      - uses: ./src
      - name: Build image
        run: docker build . -t $DOCKER_REPO/$DOCKER_REGISTRY/xo-back-api:${GITHUB_REF:11}
      - name: Push image to registry
        run: docker push $DOCKER_REPO/$DOCKER_REGISTRY/xo-back-api:${GITHUB_REF:11}